locale: en
title: Jinyu Luo
subtitle: Personal Projects & Blog
url: https://jinyuluo.github.io
logo: /assets/images/IDfoto.jpg
description: >- 
  A personal blog and project showcase.
show_downloads: false
theme: jekyll-theme-minimal
